# Generated by Django 4.1.3 on 2022-11-22 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('token', models.CharField(blank=True, default=uuid.UUID('53e8bc8b-90f5-4028-9ef5-63511b53b04f'), editable=False, max_length=200)),
            ],
        ),
    ]
